### ISSUE TITLE
NOT WORKING

### ISSUE THREAD

**Issue by cool00geek** [hexalellogram/mac-setup#1]
Won't work on my OS n00b!

Plz fix

**Comment by hexalellogram** [comment]
dont ask for eta

**Comment by cool00geek** [comment]
STILL NOT WORKING.... ETA PLZZZZZZZZZZ

BEER IF I HELPED

**Comment by cool00geek** [comment]
NOT WORKING YET. PLZ REOPEN

BAD DEV
