### ISSUE TITLE
Automate installation of Steam games

### ISSUE THREAD

**Issue by hexalellogram** [hexalellogram/mac-setup#4]
## Steps:
1. `brew cask install steamcmd`
2. prompt for username
3. prompt for password
4. echo "Installing GAME_NAME"
5. `steamcmd +login $username $password +app_update APP_ID validate`
6. `steamcmd` will ask for the Steam Guard code the first time, all other times it will used cached credentials
7. Repeat sterp 5 for all apps

## App IDs
440 - Team Fortress 2
220200 - Kerbal Space Program
233250 - Planetary Annihilation
8930 - Civilization V
99611 - Civ and Scenario Pack - Denmark
102001 - Civ and Scenario Pack - Denmark (Mac)
99612 - Civ and Scenario Pack - Korea
34495 - Civ and Scenario Pack - Mongols, Genghis Khan (Mac)
99610 - Civ and Scenario Pack - Polynesia
102000 - Civ and Scenario Pack - Polynesia (Mac)
34498 - Civ Pack - Babylon Nebuchadnezzar II (Mac)
34496 - Civilization V: Explorer’s Map Pack Mac
210450 - Civilization V: Gods & Kings Mac
102003 - CivilizationV-DLC Ancient Wonders Mac
102002 - CivilizationV-DLC Korea Mac
266720 - Conquest of the New World Deluxe Scenario
34492 - Cradle of Civilization - Americas (Mac)
34491 - Cradle of Civilization - Asia (Mac)
34490 - Cradle of Civilization - Mediterranean (Mac)
34493 - Cradle of Civilization - Mesopotamia (Mac)
34497 - Double Civ and Scenario Pack - Spain, Isabella and Inca, Pachacuti (Mac)
99613 - Scenario Pack - Ancient Wonders
16870 - Sid Meier's Civilization V - Gods and Kings
235580 - Sid Meier's Civilization V: Brave New World
235584 - Sid Meier's Civilization V: Scrambled Continents Map Pack
235585 - Sid Meier's Civilization V: Scrambled Nations Map Pack

## Run In Background
`osascript -e 'tell app "Terminal" to do script "cd $PWD && ./SteamScript.sh"'`
where `SteamScript.sh` is the script we want to use to automate Steam setup (assuming `SteamScript.sh` is in the same folder as the main script
Then we can begin installing games immediately after Steam finishes installing

## Notes
- possible: making the steam script .sh invoke steamcmd's scripting ability through .txt files

## steamcmd documentation:
https://developer.valvesoftware.com/wiki/SteamCMD

**Comment by hexalellogram** [comment]
## Run In Background
`osascript -e 'tell app "Terminal" to do script "cd ~/Git/mac-setup && ./SteamScript.sh"'`
where SteamScript.sh is the script we want to use to automate Steam setup
Then we can begin installing games immediately after Steam finishes installing

**Comment by cool00geek** [comment]
For the run in background part, you can just say `bash SteamScript.sh &` which is a bash feature to run the script, `SteamScript.sh` in the background. You don't have to use that applescript (easier and more efficient)

Note that it will still print the echo statements even though it's running in the background.

**Comment by hexalellogram** [comment]
I specifically wanted it in a new window so it didn’t interfere with the other script while it’s running. That’s why I’m using `osascript`

**Comment by hexalellogram** [comment]
added in e204648
